main: "com.soyaldo.simplemessaging.SimpleMessaging"
name: "SimpleMessaging"
version: '${project.version}'
api-version: '1.16'
softdepend: [ "PlaceholderAPI" ]
authors: [ "SoyAldo" ]
description: "Send messages with servers with redis."
website: "https://soyaldo.com/docs/simplemessaging"

commands:
  simplemessaging:
    description: "Command to manage this plugin."
    aliases:
      - "smessaging"
      - "messaging"

permissions:
  simplemessageing.admin:
    description: "Permission to access /simplemessaging command."